WellCommerce\Bundle\ProductBundle\Entity\Variant\Option:
    type: entity
    table: variant_option
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    manyToOne:
        variant:
            targetEntity: WellCommerce\Bundle\ProductBundle\Entity\Variant
            fetch: LAZY
            inversedBy: options
            joinColumns:
                variant_id:
                    referencedColumnName: id
                    onDelete: CASCADE
        attribute:
            targetEntity: WellCommerce\Bundle\AttributeBundle\Entity\Attribute
            fetch: LAZY
            joinColumns:
                attribute_id:
                    referencedColumnName: id
                    onDelete: CASCADE
        attributeValue:
            targetEntity: WellCommerce\Bundle\AttributeBundle\Entity\AttributeValue
            fetch: LAZY
            joinColumns:
                attribute_value_id:
                    referencedColumnName: id
                    onDelete: CASCADE

