well_commerce_product:
    configuration:
        product:
            orm:
                factory: WellCommerce\Bundle\ProductBundle\Factory\ProductFactory
                repository: WellCommerce\Bundle\ProductBundle\Repository\ProductRepository
                mapping: "@WellCommerceProductBundle/Resources/config/doctrine/Product.orm.yml"
                entity: WellCommerce\Bundle\ProductBundle\Entity\Product
            api:
                exposed: true
                dataset: product.dataset.admin
                manager: product.manager
            dynamic_routing:
                entity: WellCommerce\Bundle\ProductBundle\Entity\ProductRoute
                generator: WellCommerce\Bundle\ProductBundle\Routing\ProductRouteGenerator
                defaults:
                    _controller: product.controller.front:indexAction
        variant:
            orm:
                factory: WellCommerce\Bundle\ProductBundle\Factory\VariantFactory
                repository: WellCommerce\Bundle\ProductBundle\Repository\VariantRepository
                mapping: "@WellCommerceProductBundle/Resources/config/doctrine/Variant.orm.yml"
                entity: WellCommerce\Bundle\ProductBundle\Entity\Variant
        variant_option:
            orm:
                factory: WellCommerce\Bundle\ProductBundle\Factory\VariantOptionFactory
                repository: WellCommerce\Bundle\ProductBundle\Repository\VariantOptionRepository
                mapping: "@WellCommerceProductBundle/Resources/config/doctrine/VariantOption.orm.yml"
                entity: WellCommerce\Bundle\ProductBundle\Entity\VariantOption
        product_photo:
            orm:
                repository: WellCommerce\Bundle\ProductBundle\Repository\ProductPhotoRepository
                mapping: "@WellCommerceProductBundle/Resources/config/doctrine/ProductPhoto.orm.yml"
                entity: WellCommerce\Bundle\ProductBundle\Entity\ProductPhoto
        product_route:
            orm:
                mapping: "@WellCommerceProductBundle/Resources/config/doctrine/ProductRoute.orm.yml"
                entity: WellCommerce\Bundle\ProductBundle\Entity\ProductRoute
        product_translation:
            orm:
                mapping: "@WellCommerceProductBundle/Resources/config/doctrine/ProductTranslation.orm.yml"
                entity: WellCommerce\Bundle\ProductBundle\Entity\ProductTranslation
