well_commerce_product:
    configuration:
        product:
            orm:
                factory: WellCommerce\Bundle\ProductBundle\Factory\ProductFactory
                repository: WellCommerce\Bundle\ProductBundle\Repository\ProductRepository
                mapping: "@WellCommerceProductBundle/Resources/config/doctrine/Product.orm.yml"
                entity: WellCommerce\Bundle\ProductBundle\Entity\Product
            api:
                exposed: true
                dataset: product.dataset.admin
                manager: product.manager
            dynamic_routing:
                entity: WellCommerce\Bundle\ProductBundle\Entity\ProductRoute
                generator: WellCommerce\Bundle\ProductBundle\Routing\ProductRouteGenerator
                defaults:
                    _controller: product.controller.front:indexAction
        product_distinction:
            orm:
                factory: WellCommerce\Bundle\ProductBundle\Factory\ProductDistinctionFactory
                repository: WellCommerce\Bundle\ProductBundle\Repository\ProductDistinctionRepository
                mapping: "@WellCommerceProductBundle/Resources/config/doctrine/ProductDistinction.orm.yml"
                entity: WellCommerce\Bundle\ProductBundle\Entity\ProductDistinction
        variant:
            orm:
                factory: WellCommerce\Bundle\ProductBundle\Factory\VariantFactory
                repository: WellCommerce\Bundle\ProductBundle\Repository\VariantRepository
                mapping: "@WellCommerceProductBundle/Resources/config/doctrine/Variant.orm.yml"
                entity: WellCommerce\Bundle\ProductBundle\Entity\Variant
        variant_option:
            orm:
                factory: WellCommerce\Bundle\ProductBundle\Factory\VariantOptionFactory
                repository: WellCommerce\Bundle\ProductBundle\Repository\VariantOptionRepository
                mapping: "@WellCommerceProductBundle/Resources/config/doctrine/VariantOption.orm.yml"
                entity: WellCommerce\Bundle\ProductBundle\Entity\VariantOption
        product_photo:
            orm:
                repository: WellCommerce\Bundle\ProductBundle\Repository\ProductPhotoRepository
                mapping: "@WellCommerceProductBundle/Resources/config/doctrine/ProductPhoto.orm.yml"
                entity: WellCommerce\Bundle\ProductBundle\Entity\ProductPhoto
        product_route:
            orm:
                mapping: "@WellCommerceProductBundle/Resources/config/doctrine/ProductRoute.orm.yml"
                entity: WellCommerce\Bundle\ProductBundle\Entity\ProductRoute
        product_translation:
            orm:
                manager: false
                mapping: "@WellCommerceProductBundle/Resources/config/doctrine/ProductTranslation.orm.yml"
                entity: WellCommerce\Bundle\ProductBundle\Entity\ProductTranslation

well_commerce_search:
    engine:
        index:
            types:
                product:
                    class: WellCommerce\Bundle\ProductBundle\Search\ProductType
                    mapping:
                        sku:
                            indexable: true
                            boost: 1
                            fuzziness: 2
                            value_expression: resource.getSku()
                        name:
                            indexable: true
                            boost: 1
                            fuzziness: 3
                            value_expression: resource.translate(locale).getName()
                        short_description:
                            indexable: true
                            boost: 0.5
                            fuzziness: 0
                            value_expression: resource.translate(locale).getShortDescription()
                        description:
                            indexable: true
                            boost: 0.5
                            fuzziness: 0
                            value_expression: resource.translate(locale).getDescription()
                        producer:
                            indexable: true
                            boost: 0.5
                            fuzziness: 2
                            value_expression: resource.getProducer().translate(locale).getName()
                        category:
                            indexable: true
                            boost: 0.5
                            fuzziness: 2
                            value_expression: resource.getCategories().first().translate(locale).getName()
