WellCommerce\Bundle\ProductBundle\Entity\ProductPhoto:
    fields:
        id:
            groups:
                - default
                - photo
        mainPhoto:
            groups:
                - default
                - photo
        hierarchy:
            groups:
                - default
                - photo
        createdAt:
            groups: {  }
        updatedAt:
            groups: {  }
    associations:
        photo:
            groups:
                - photo
        product:
            groups:
                - photo
    callbacks: {  }
