WellCommerce\Bundle\ProductBundle\Entity\Product\Route:
    fields:
        id:
            groups:
                - default
                - route
        path:
            groups:
                - default
                - route
        locale:
            groups:
                - default
                - route
    associations:
        identifier:
            groups:
                - route
    callbacks: {  }
