WellCommerce\Bundle\ProductBundle\Entity\ProductDistinction:
    fields:
        id:
            groups:
                - default
                - distinction
        validFrom:
            groups:
                - default
                - distinction
        validTo:
            groups:
                - default
                - distinction
    associations:
        status:
            groups:
                - distinction
