WellCommerce\Bundle\ProductBundle\Entity\ProductPhoto:
    fields:
        id:
            groups:
                - default
                - photo
        mainPhoto:
            groups:
                - default
                - photo
        hierarchy:
            groups:
                - default
                - photo
    associations:
        photo:
            groups:
                - photo
