WellCommerce\Bundle\ProductBundle\Entity\Product:
    fields:
        id:
            groups:
                - default
                - product
        sku:
            groups:
                - default
                - product
        stock:
            groups:
                - default
                - product
        trackStock:
            groups:
                - default
                - product
        weight:
            groups:
                - default
                - product
        packageSize:
            groups:
                - default
                - product
        enabled:
            groups:
                - default
                - product
        hierarchy:
            groups:
                - default
                - product
        buyPrice:
            groups:
                - default
                - product
        sellPrice:
            groups:
                - default
                - product
        dimension:
            groups:
                - default
                - product
    associations:
        productPhotos:
            groups:
                - product
        variants:
            groups:
                - product
        distinctions:
            groups:
                - product
        producer:
            groups:
                - product
        unit:
            groups:
                - product
        availability:
            groups:
                - product
        buyPriceTax:
            groups:
                - product
        sellPriceTax:
            groups:
                - product
        attributeGroup:
            groups:
                - product
        photo:
            groups:
                - product
        categories:
            groups:
                - product
        translations:
            groups:
                - product
        shops:
            groups:
                - product
