WellCommerce\Bundle\ProductBundle\Entity\ProductTranslation:
    fields:
        name:
            groups:
                - default
                - product_translation
        shortDescription:
            groups:
                - default
                - product_translation
        description:
            groups:
                - default
                - product_translation
        slug:
            groups:
                - default
                - product_translation
        meta:
            groups:
                - default
                - product_translation
        locale:
            groups:
                - default
                - product_translation
