WellCommerce\Bundle\ProductBundle\Entity\Variant:
    fields:
        id:
            groups:
                - default
                - variant
        weight:
            groups:
                - default
                - variant
        symbol:
            groups:
                - default
                - variant
        stock:
            groups:
                - default
                - variant
        modifierType:
            groups:
                - default
                - variant
        modifierValue:
            groups:
                - default
                - variant
        hierarchy:
            groups:
                - default
                - variant
        sellPrice:
            groups:
                - default
                - variant
    associations:
        options:
            groups:
                - default
                - variant
        availability:
            groups:
                - variant
        photo:
            groups:
                - variant
