WellCommerce\Bundle\ProductBundle\Entity\VariantOption:
    fields:
        id:
            groups:
                - default
                - option
    associations:
        attributeValue:
            groups:
                - option
                - default
