WellCommerce\Bundle\ProductBundle\Entity\VariantOption:
    fields:
        id:
            groups:
                - default
                - option
    associations:
        variant:
            groups:
                - option
        attribute:
            groups:
                - option
        attributeValue:
            groups:
                - option
