# WellCommerce Open-Source E-Commerce Platform
#
# This file is part of the WellCommerce package.
# (c) Adam Piotrowski <adam@wellcommerce.org>
#
# For the full copyright and license information,
# please view the LICENSE file that was distributed with this source code.

well_commerce_api:
    request_handler:
        product:
            manager: product.manager
    serialization:
        WellCommerce\Bundle\ProductBundle\Entity\Product:
            mapping: "@WellCommerceProductBundle/Resources/config/serialization/Product.yml"
        WellCommerce\Bundle\ProductBundle\Entity\Product\Distinction:
            mapping: "@WellCommerceProductBundle/Resources/config/serialization/Product/Distinction.yml"
        WellCommerce\Bundle\ProductBundle\Entity\Variant:
            mapping: "@WellCommerceProductBundle/Resources/config/serialization/Variant.yml"
        WellCommerce\Bundle\ProductBundle\Entity\Variant\Option:
            mapping: "@WellCommerceProductBundle/Resources/config/serialization/Variant/Option.yml"
        WellCommerce\Bundle\ProductBundle\Entity\Product\Photo:
            mapping: "@WellCommerceProductBundle/Resources/config/serialization/Product/Photo.yml"
        WellCommerce\Bundle\ProductBundle\Entity\Product\Route:
            mapping: "@WellCommerceProductBundle/Resources/config/serialization/Product/Route.yml"
        WellCommerce\Bundle\ProductBundle\Entity\ProductTranslation:
            mapping: "@WellCommerceProductBundle/Resources/config/serialization/ProductTranslation.yml"
