# WellCommerce Open-Source E-Commerce Platform
#
# This file is part of the WellCommerce package.
# (c) Adam Piotrowski <adam@wellcommerce.org>
#
# For the full copyright and license information,
# please view the LICENSE file that was distributed with this source code.

well_commerce_doctrine:
    configuration:
        product:
            factory: WellCommerce\Bundle\ProductBundle\Factory\ProductFactory
            repository: WellCommerce\Bundle\ProductBundle\Repository\ProductRepository
            mapping: "@WellCommerceProductBundle/Resources/config/doctrine/Product.orm.yml"
            entity: WellCommerce\Bundle\ProductBundle\Entity\Product
        product_distinction:
            factory: WellCommerce\Bundle\ProductBundle\Factory\Product\DistinctionFactory
            repository: WellCommerce\Bundle\ProductBundle\Repository\Product\DistinctionRepository
            mapping: "@WellCommerceProductBundle/Resources/config/doctrine/Product/Distinction.orm.yml"
            entity: WellCommerce\Bundle\ProductBundle\Entity\Product\Distinction
        variant:
            factory: WellCommerce\Bundle\ProductBundle\Factory\VariantFactory
            repository: WellCommerce\Bundle\ProductBundle\Repository\VariantRepository
            mapping: "@WellCommerceProductBundle/Resources/config/doctrine/Variant.orm.yml"
            entity: WellCommerce\Bundle\ProductBundle\Entity\Variant
        variant_option:
            factory: WellCommerce\Bundle\ProductBundle\Factory\Variant\OptionFactory
            repository: WellCommerce\Bundle\ProductBundle\Repository\Variant\OptionRepository
            mapping: "@WellCommerceProductBundle/Resources/config/doctrine/Variant/Option.orm.yml"
            entity: WellCommerce\Bundle\ProductBundle\Entity\Variant\Option
        product_photo:
            repository: WellCommerce\Bundle\ProductBundle\Repository\Product\PhotoRepository
            mapping: "@WellCommerceProductBundle/Resources/config/doctrine/Product/Photo.orm.yml"
            entity: WellCommerce\Bundle\ProductBundle\Entity\Product\Photo
        product_route:
            mapping: "@WellCommerceProductBundle/Resources/config/doctrine/Product/Route.orm.yml"
            entity: WellCommerce\Bundle\ProductBundle\Entity\Product\Route
        product_translation:
            mapping: "@WellCommerceProductBundle/Resources/config/doctrine/ProductTranslation.orm.yml"
            entity: WellCommerce\Bundle\ProductBundle\Entity\ProductTranslation
