# WellCommerce Open-Source E-Commerce Platform
#
# This file is part of the WellCommerce package.
# (c) Adam Piotrowski <adam@wellcommerce.org>
#
# For the full copyright and license information,
# please view the LICENSE file that was distributed with this source code.

well_commerce_search:
    engine:
        index:
            types:
                product:
                    class: WellCommerce\Bundle\ProductBundle\Search\ProductType
                    mapping:
                        sku:
                            indexable: true
                            boost: 1
                            fuzziness: 2
                            value_expression: resource.getSku()
                        name:
                            indexable: true
                            boost: 1
                            fuzziness: 3
                            value_expression: resource.translate(locale).getName()
                        short_description:
                            indexable: true
                            boost: 0.5
                            fuzziness: 0
                            value_expression: resource.translate(locale).getShortDescription()
                        description:
                            indexable: true
                            boost: 0.5
                            fuzziness: 0
                            value_expression: resource.translate(locale).getDescription()
                        producer:
                            indexable: true
                            boost: 0.5
                            fuzziness: 2
                            value_expression: resource.getProducer().translate(locale).getName()
                        category:
                            indexable: true
                            boost: 0.5
                            fuzziness: 2
                            value_expression: resource.getCategories().first().translate(locale).getName()
